name: Build Argus APK
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - uses: android-actions/setup-android@v3

      - name: Install Android SDK components
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Generate Wrapper
        run: gradle wrapper --gradle-version 8.7

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Debug APK (full logs + fail on error)
        shell: bash
        run: |
          set -euo pipefail
          ./gradlew :app:clean :app:assembleDebug --stacktrace --info --console=plain 2>&1 | tee gradle-build.log

      - name: List outputs
        if: always()
        run: ls -R app/build/outputs || true

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Argus-APK
          path: app/build/outputs/**/*.apk
          if-no-files-found: error

      - name: Upload Gradle log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-build-log
          path: gradle-build.log
