name: Build Argus APK
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle (cache)
        uses: gradle/actions/setup-gradle@v3

      # Se o wrapper não estiver no repo, gera um novo
      - name: Generate Wrapper (8.7)
        run: |
          gradle --version
          gradle wrapper --gradle-version 8.7
          chmod +x ./gradlew
        shell: bash

      - name: Assemble Debug (full logs)
        run: ./gradlew :app:assembleDebug --stacktrace --info --no-daemon

      - name: List outputs
        run: ls -R app/build/outputs || true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Argus-debug-apk
          path: app/build/outputs/apk/debug/*.apk
