name: Build Argus APK
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - uses: android-actions/setup-android@v3

      - name: Install Android SDK components
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Generate Wrapper
        run: gradle wrapper --gradle-version 8.7

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Process resources only (debug)
        run: ./gradlew :app:processDebugResources --stacktrace --info --console=plain | tee gradle-res.log

      - name: Grep resource errors
        if: always()
        run: |
          echo "==== Direct matches (AAPT/SAX) ===="
          grep -nE "AAPT: error|SAXParseException|error:.*file|error: resource" gradle-res.log || true
          echo
          echo "==== Last 200 log lines ===="
          tail -n 200 gradle-res.log || true

      - name: Upload res log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-res-log
          path: gradle-res.log
