name: Build Argus APK
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - uses: android-actions/setup-android@v3

      - name: Install Android SDK components
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Generate Wrapper
        run: gradle wrapper --gradle-version 8.7

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Clean
        run: ./gradlew clean --stacktrace --console=plain

      - name: Compile Debug Kotlin (log completo)
        run: ./gradlew :app:compileDebugKotlin --stacktrace --info --console=plain --max-workers=1 2>&1 | tee gradle-compile-kotlin.log

      - name: Assemble Debug (log completo)
        run: ./gradlew :app:assembleDebug --stacktrace --info --console=plain --max-workers=1 2>&1 | tee gradle-assemble.log

      - name: Dependências (classpath)
        run: |
          ./gradlew -q :app:dependencies --configuration debugCompileClasspath > deps-compile.txt || true
          ./gradlew -q :app:dependencies --configuration debugRuntimeClasspath > deps-runtime.txt || true

      - name: List outputs
        if: always()
        run: ls -R app/build/outputs || true

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Argus-APK
          path: app/build/outputs/**/*.apk
          if-no-files-found: error

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            gradle-compile-kotlin.log
            gradle-assemble.log
            deps-compile.txt
            deps-runtime.txt
