name: Build Argus APK
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - uses: android-actions/setup-android@v3

      - name: Install Android SDK components
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      # Gera o wrapper na RAIZ do repo e garante que existe
      - name: Generate Gradle Wrapper (root)
        working-directory: ${{ github.workspace }}
        run: |
          gradle wrapper --gradle-version 8.7
          ls -la
          test -f gradlew || (echo "::error::gradlew not generated at repo root" && exit 1)
          chmod +x gradlew

      - name: Clean
        run: ./gradlew clean --no-daemon

      - name: Assemble Debug (log completo)
        run: ./gradlew :app:assembleDebug --stacktrace --info --console=plain --no-daemon | tee gradle-assemble.log

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: argus-apk-debug
          path: app/build/outputs/apk/debug/*.apk

      - name: Upload logs (sempre)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-logs
          path: |
            gradle-assemble.log
            app/build/outputs/logs/**
