name: Build Argus APK
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - uses: android-actions/setup-android@v3

      - name: Install Android SDK components
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      # Executa o build usando Gradle 8.7 sem precisar do gradlew
      - name: Build Debug APK (no wrapper)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          arguments: >
            clean :app:assembleDebug
            --stacktrace --warning-mode all --console=plain

      - name: List outputs
        run: |
          echo "== outputs =="
          find app/build/outputs -maxdepth 3 -type f -print || true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: argus-debug-apk
          path: app/build/outputs/apk/debug/*.apk
